SiteTitle: AconCavy
PageTitle: |
  =>
  {
    var siteTitle = Context.GetString("SiteTitle");
    var title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{siteTitle} - {title}");
  }

ProfileSources: profiles/
WorkSources: works/
PublicationSources: authored/
CoPublicationSources: coauthored/
Layout: /_Layout.cshtml
Copyright: => $"Copyright © 2020-{DateTime.Now.Year} AconCavy"
